# Generated by Django 3.1 on 2020-08-10 07:38

from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models
import mapbox_location_field.spatial.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', mapbox_location_field.models.AddressAutoHiddenField(map_id='map', null=True)),
                ('email', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=256)),
                ('location', mapbox_location_field.spatial.models.SpatialLocationField(map_attrs={}, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site_Facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.CharField(max_length=256)),
                ('pitch_type', models.CharField(max_length=256)),
                ('pitch_level', models.CharField(max_length=256)),
                ('hook_up', models.CharField(max_length=256)),
                ('waste', models.CharField(max_length=256)),
                ('toilets', models.CharField(max_length=256)),
                ('ambience', models.CharField(max_length=256)),
                ('security', models.CharField(max_length=256)),
                ('wifi', models.CharField(max_length=256)),
                ('tv_signal', models.CharField(max_length=256)),
                ('phone_signal_3G_4G', models.CharField(max_length=256)),
                ('pets', models.CharField(max_length=256)),
                ('children', models.CharField(max_length=256)),
                ('laundry', models.CharField(max_length=256)),
                ('cost_charges', models.FloatField()),
                ('cost_extras', models.FloatField()),
                ('cost_currency', models.CharField(max_length=3)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triplog.site_information')),
            ],
        ),
        migrations.CreateModel(
            name='Journey_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('weather', models.CharField(max_length=256)),
                ('travel_from', models.CharField(max_length=256)),
                ('travel_to', models.CharField(max_length=256)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.TimeField()),
                ('mileage_start', models.FloatField()),
                ('mileage_end', models.FloatField()),
                ('distance', models.FloatField()),
                ('toll_charges', models.FloatField()),
                ('toll_currency', models.CharField(max_length=3)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now_add=True)),
                ('star_rating', models.CharField(max_length=256)),
                ('would_return', models.BooleanField()),
                ('notes', models.CharField(max_length=1024)),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='triplog.site_information')),
            ],
        ),
    ]
