# Generated by Django 3.1 on 2020-08-13 14:24

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0002_auto_20200810_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_facilities',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 8, 13, 14, 23, 54, 172648, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site_facilities',
            name='edited_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
