# Generated by Django 3.1 on 2020-08-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0003_auto_20200813_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey_details',
            name='notes',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='journey_details',
            name='would_return',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='site_facilities',
            name='children',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='site_facilities',
            name='greeting',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Indifferent', 'Indifferent')], max_length=256),
        ),
        migrations.AlterField(
            model_name='site_facilities',
            name='laundry',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='site_facilities',
            name='pets',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='site_facilities',
            name='pitch_level',
            field=models.CharField(blank=True, choices=[('Level', 'Level'), ('Gentle Slope', 'Gentle Slope'), ('Steep Slope', 'Steep Slope'), ('Impossible Slope', 'Impossible Slope')], max_length=256),
        ),
        migrations.AlterField(
            model_name='site_facilities',
            name='pitch_type',
            field=models.CharField(blank=True, choices=[('Level', 'Level'), ('Gentle Slope', 'Gentle Slope'), ('Steep Slope', 'Steep Slope'), ('Impossible Slope', 'Impossible Slope')], max_length=256),
        ),
        migrations.AlterField(
            model_name='site_facilities',
            name='wifi',
            field=models.BooleanField(blank=True),
        ),
    ]
