# Generated by Django 3.1 on 2020-08-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0007_sitefacilities_laundry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeydetail',
            name='end_date',
            field=models.DateField(),
        ),
    ]
