# Generated by Django 3.1 on 2020-08-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0009_auto_20200816_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeydetail',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journeydetail',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
