# Generated by Django 3.1 on 2020-08-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0010_auto_20200816_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeydetail',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='journeydetail',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journeydetail',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journeydetail',
            name='edited_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='journeydetail',
            name='mileage_end',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journeydetail',
            name='notes',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='journeydetail',
            name='toll_charges',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journeydetail',
            name='would_return',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
