# Generated by Django 3.1 on 2020-09-05 13:58

from django.db import migrations, models
import mapbox_location_field.spatial.models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0012_auto_20200825_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinformation',
            name='edited_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='location',
            field=mapbox_location_field.spatial.models.SpatialLocationField(blank=True, map_attrs={'center': [-0.82761, 51.18225]}, null=True, srid=4326),
        ),
    ]
