# Generated by Django 3.1 on 2020-09-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0014_auto_20200907_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeydetail',
            name='edited_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
