# Generated by Django 3.1 on 2020-09-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0015_auto_20200907_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinformation',
            name='cost_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='cost_extras',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='pitch_type',
            field=models.CharField(blank=True, choices=[('DIRT', 'Dirt'), ('Grass', 'Grass'), ('Hardstanding', 'Hardstanding')], max_length=256),
        ),
    ]
