# Generated by Django 3.1 on 2020-09-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0016_auto_20200907_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='notes',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
