# Generated by Django 3.1 on 2020-09-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0016_auto_20200911_1135'),
        ('triplog', '0017_siteinformation_notes'),
    ]

    operations = [
    ]
