# Generated by Django 3.1 on 2020-10-23 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('triplog', '0028_auto_20201022_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journeydetail',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='journeydetail',
            name='edited_date',
        ),
        migrations.RemoveField(
            model_name='siteinformation',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='siteinformation',
            name='edited_date',
        ),
        migrations.AddField(
            model_name='journeydetail',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='journey_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journeydetail',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='journey_edited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='site_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='site_edited', to=settings.AUTH_USER_MODEL),
        ),
    ]
