# Generated by Django 3.1 on 2020-10-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0033_auto_20201023_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journeydetail',
            name='created',
        ),
        migrations.RemoveField(
            model_name='journeydetail',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='siteinformation',
            name='created',
        ),
        migrations.RemoveField(
            model_name='siteinformation',
            name='edited',
        ),
    ]
