# Generated by Django 3.1 on 2020-10-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0036_auto_20201023_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeydetail',
            name='created_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='journeydetail',
            name='edited_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='created_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='edited_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
