# Generated by Django 3.1 on 2020-10-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0037_auto_20201023_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journeydetail',
            name='created_name',
        ),
        migrations.RemoveField(
            model_name='journeydetail',
            name='edited_name',
        ),
        migrations.RemoveField(
            model_name='siteinformation',
            name='created_name',
        ),
        migrations.RemoveField(
            model_name='siteinformation',
            name='edited_name',
        ),
    ]
