# Generated by Django 3.1 on 2020-11-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0042_auto_20201026_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeydetail',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journeydetail',
            name='toll_currency',
            field=models.CharField(blank=True, choices=[('EUR', '€'), ('GBP', '£'), ('USD', '$'), ('CHF', 'CHF')], default='GBP', max_length=3),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='cost_currency',
            field=models.CharField(blank=True, choices=[('EUR', '€'), ('GBP', '£'), ('USD', '$'), ('CHF', 'CHF')], default='GBP', max_length=3),
        ),
    ]
