# Generated by Django 3.1 on 2020-11-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0044_auto_20201109_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='days_stayed',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
