# Generated by Django 3.1 on 2020-11-15 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0047_auto_20201115_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripdetails',
            name='sites',
        ),
        migrations.RemoveField(
            model_name='tripjourney',
            name='type',
        ),
        migrations.DeleteModel(
            name='TripSite',
        ),
    ]
