# Generated by Django 3.1 on 2020-11-16 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0048_auto_20201115_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripdetails',
            name='journeys',
        ),
        migrations.AddField(
            model_name='tripdetails',
            name='journeys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='journeys', to='triplog.journeydetail'),
        ),
        migrations.DeleteModel(
            name='TripJourney',
        ),
    ]
