# Generated by Django 3.1 on 2020-11-18 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mapbox_location_field.models
import mapbox_location_field.spatial.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trip_created_by', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trip_edited_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SiteInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', mapbox_location_field.models.AddressAutoHiddenField(map_id='map')),
                ('email', models.CharField(blank=True, max_length=256)),
                ('siteowner', models.CharField(blank=True, choices=[('CAMC CL', 'CAMC CL'), ('CAMC Site', 'CAMC Site'), ('C&CC CL', 'C&CC CL'), ('C&CC Site', 'C&CC Site'), ('Independent', 'Independent'), ('France Passion', 'France Passion'), ('n/a', 'n/a')], default='n/a', max_length=256)),
                ('phone_number', models.CharField(blank=True, max_length=256)),
                ('location', mapbox_location_field.spatial.models.SpatialLocationField(blank=True, map_attrs={'center': [-0.82761, 51.18225]}, null=True, srid=4326)),
                ('star_rating', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True)),
                ('would_return', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No'), (None, 'n/a')], default=True, null=True)),
                ('greeting', models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Indifferent', 'Indifferent')], default='Good', max_length=256)),
                ('pitch_type', models.CharField(blank=True, choices=[('Dirt', 'Dirt'), ('Grass', 'Grass'), ('Hardstanding', 'Hardstanding')], default='Hardstanding', max_length=256)),
                ('pitch_level', models.CharField(blank=True, choices=[('Level', 'Level'), ('Gentle Slope', 'Gentle Slope'), ('Steep Slope', 'Steep Slope'), ('Impossible Slope', 'Impossible Slope')], default='Level', max_length=256)),
                ('hook_up', models.CharField(blank=True, choices=[('6A', '6A'), ('10A', '10A'), ('16A', '16A')], default='16A', max_length=256)),
                ('waste', models.CharField(blank=True, choices=[('On Pitch', 'On Pitch'), ('Close By', 'Close By'), ('Miles Away', 'Miles Away')], default='Close By', max_length=256)),
                ('toilets', models.CharField(blank=True, choices=[('None', 'None'), ('Clean', 'Clean'), ('Dirty', 'Dirty'), ("Don't Go There", "Don't Go There")], default='Clean', max_length=256)),
                ('ambience', models.CharField(blank=True, choices=[('Peaceful', 'Peaceful'), ('OK', 'OK'), ('Loud/Lively', 'Loud/Lively')], default='Peaceful', max_length=256)),
                ('security', models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Poor', 'Poor')], default='Good', max_length=256)),
                ('wifi', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No'), (None, 'n/a')], default=None, null=True)),
                ('tv_signal', models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Poor', 'Poor'), ('n/a', 'n/a')], default='n/a', max_length=256)),
                ('phone_signal_3G_4G', models.CharField(blank=True, choices=[('Excellent 4G', 'Excellent 4G'), ('Good 4G', 'Good 4G'), ('Poor 4G', 'Poor 4G'), ('Excellent 3G', 'Excellent 3G'), ('Good 3G', 'Good 3G'), ('Poor 3G', 'Poor 3G')], default='Good 4G', max_length=256)),
                ('pets', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No'), (None, 'n/a')], default=True, null=True)),
                ('children', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No'), (None, 'n/a')], default=False, null=True)),
                ('laundry', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No'), (None, 'n/a')], default=False, null=True)),
                ('cost_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cost_extras', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cost_currency', models.CharField(blank=True, choices=[('EUR', '€'), ('GBP', '£'), ('USD', '$'), ('CHF', 'CHF')], default='GBP', max_length=3)),
                ('notes', models.CharField(blank=True, max_length=1024, null=True)),
                ('days_stayed', models.IntegerField(blank=True, default=1, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='site_created_by', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='site_edited_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JourneyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('weather', models.CharField(blank=True, max_length=256)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('mileage_start', models.IntegerField()),
                ('mileage_end', models.IntegerField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('toll_charges', models.FloatField(blank=True, null=True)),
                ('toll_currency', models.CharField(blank=True, choices=[('EUR', '€'), ('GBP', '£'), ('USD', '$'), ('CHF', 'CHF')], default='GBP', max_length=3)),
                ('notes', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='journey_created_by', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='journey_edited_by', to=settings.AUTH_USER_MODEL)),
                ('travel_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_travel_from', to='triplog.siteinformation')),
                ('travel_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_travel_to', to='triplog.siteinformation')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='journey_trip', to='triplog.tripdetail')),
            ],
        ),
    ]
