# Generated by Django 3.1 on 2020-11-22 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0002_tripdetail_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeydetail',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='journeydetails', to='triplog.tripdetail'),
        ),
    ]
