# Generated by Django 3.0.8 on 2020-08-05 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0002_auto_20200805_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey_details',
            name='destination',
        ),
    ]
