# Generated by Django 3.0.8 on 2020-08-05 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0003_remove_journey_details_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey_details',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='triplog.Site_Information'),
        ),
    ]
