# Generated by Django 3.0.8 on 2020-08-07 09:58

from django.db import migrations, models
import mapbox_location_field.models
import mapbox_location_field.spatial.models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0004_journey_details_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site_information',
            name='address_code',
        ),
        migrations.RemoveField(
            model_name='site_information',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='site_information',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='site_information',
            name='address_line3',
        ),
        migrations.AddField(
            model_name='site_information',
            name='address',
            field=mapbox_location_field.models.AddressAutoHiddenField(map_id='map', null=True),
        ),
        migrations.AddField(
            model_name='site_information',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='site_information',
            name='location',
            field=mapbox_location_field.spatial.models.SpatialLocationField(map_attrs={}, null=True, srid=4326),
        ),
    ]
