# Generated by Django 3.1 on 2020-08-16 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0004_auto_20200813_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('weather', models.CharField(blank=True, max_length=256)),
                ('travel_from', models.CharField(max_length=256)),
                ('travel_to', models.CharField(blank=True, max_length=256)),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True)),
                ('duration', models.TimeField(blank=True)),
                ('mileage_start', models.FloatField()),
                ('mileage_end', models.FloatField(blank=True)),
                ('distance', models.FloatField(blank=True)),
                ('toll_charges', models.FloatField(blank=True)),
                ('toll_currency', models.CharField(blank=True, max_length=3)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now_add=True)),
                ('star_rating', models.CharField(max_length=256)),
                ('would_return', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')])),
                ('notes', models.CharField(blank=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='SiteFacilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Indifferent', 'Indifferent')], max_length=256)),
                ('pitch_type', models.CharField(blank=True, choices=[('Level', 'Level'), ('Gentle Slope', 'Gentle Slope'), ('Steep Slope', 'Steep Slope'), ('Impossible Slope', 'Impossible Slope')], max_length=256)),
                ('pitch_level', models.CharField(blank=True, choices=[('Level', 'Level'), ('Gentle Slope', 'Gentle Slope'), ('Steep Slope', 'Steep Slope'), ('Impossible Slope', 'Impossible Slope')], max_length=256)),
                ('hook_up', models.CharField(blank=True, choices=[('6A', '6A'), ('10A', '10A'), ('16A', '16A')], max_length=256)),
                ('waste', models.CharField(blank=True, choices=[('On Pitch', 'On Pitch'), ('Close By', 'Close By'), ('Miles Away', 'Miles Away')], max_length=256)),
                ('toilets', models.CharField(blank=True, choices=[('None', 'None'), ('Clean', 'Clean'), ('Dirty', 'Dirty'), ("Don't Go There", "Don't Go There")], max_length=256)),
                ('ambience', models.CharField(blank=True, choices=[('Peaceful', 'Peaceful'), ('OK', 'OK'), ('Loud / Lively', 'Loud / Lively')], max_length=256)),
                ('security', models.CharField(blank=True, choices=[('Good', 'Good'), ('Poor', 'Poor')], max_length=256)),
                ('wifi', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')])),
                ('tv_signal', models.CharField(blank=True, choices=[('Good', 'Good'), ('Poor', 'Poor')], max_length=256)),
                ('phone_signal_3G_4G', models.CharField(blank=True, choices=[('Good', 'Good'), ('Poor', 'Poor')], max_length=256)),
                ('pets', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')])),
                ('children', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')])),
                ('cost_currency', models.CharField(blank=True, max_length=3)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='site_facilities',
            name='name',
        ),
        migrations.RenameModel(
            old_name='Site_Information',
            new_name='SiteInformation',
        ),
        migrations.DeleteModel(
            name='Journey_Details',
        ),
        migrations.DeleteModel(
            name='Site_Facilities',
        ),
        migrations.AddField(
            model_name='sitefacilities',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triplog.siteinformation'),
        ),
        migrations.AddField(
            model_name='journeydetails',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='triplog.siteinformation'),
        ),
    ]
