# Generated by Django 3.1 on 2020-11-28 19:50

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0004_siteinformation_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='addressline',
            field=mapbox_location_field.models.AddressLineField(blank=True, map_id='map', null=True),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='locality',
            field=mapbox_location_field.models.AddressLocalityField(blank=True, map_id='map', null=True),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='place',
            field=mapbox_location_field.models.AddressPlaceField(blank=True, map_id='map', null=True),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='postcode',
            field=mapbox_location_field.models.AddressPostcodeField(blank=True, map_id='map', null=True),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='region',
            field=mapbox_location_field.models.AddressRegionField(blank=True, map_id='map', null=True),
        ),
    ]
