# Generated by Django 3.1 on 2020-11-29 13:50

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0005_auto_20201128_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='district',
            field=mapbox_location_field.models.AddressDistrictField(blank=True, map_id='map', null=True),
        ),
    ]
