# Generated by Django 3.1 on 2020-08-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0005_auto_20200816_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitefacilities',
            name='cost_charges',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitefacilities',
            name='cost_extras',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
