# Generated by Django 3.1 on 2021-01-24 11:58

from django.db import migrations, models
import django.utils.timezone
import mapbox_location_field.models
import mapbox_location_field.spatial.models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0006_siteinformation_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdetail',
            name='trip_route',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='tripdetail',
            name='uploaded_trip_route_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='address',
            field=mapbox_location_field.models.AddressAutoHiddenField(map_id='map_1'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='addressline',
            field=mapbox_location_field.models.AddressLineField(blank=True, map_id='map_1', null=True),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='country',
            field=mapbox_location_field.models.AddressCountryField(blank=True, map_id='map_1', null=True),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='district',
            field=mapbox_location_field.models.AddressDistrictField(blank=True, map_id='map_1', null=True),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='locality',
            field=mapbox_location_field.models.AddressLocalityField(blank=True, map_id='map_1', null=True),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='location',
            field=mapbox_location_field.spatial.models.SpatialLocationField(blank=True, map_attrs={'center': [-0.82761, 51.18225], 'id': 'map_1', 'style': 'mapbox://styles/mapbox/satellite-streets-v11'}, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='place',
            field=mapbox_location_field.models.AddressPlaceField(blank=True, map_id='map_1', null=True),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='postcode',
            field=mapbox_location_field.models.AddressPostcodeField(blank=True, map_id='map_1', null=True),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='region',
            field=mapbox_location_field.models.AddressRegionField(blank=True, map_id='map_1', null=True),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='siteowner',
            field=models.CharField(blank=True, choices=[('CAMC CL', 'CAMC CL'), ('CAMC Site', 'CAMC Site'), ('C&CC CL', 'C&CC CL'), ('C&CC Site', 'C&CC Site'), ('Independent', 'Independent'), ('France Passion', 'France Passion'), ('Aire', 'Aire'), ('Pub', 'Pub'), ('Hotel', 'Hotel'), ('Restaurant', 'Restaurant'), ('Roadside', 'Roadside'), ('Home', 'Home'), ('n/a', 'n/a')], default='n/a', max_length=256),
        ),
    ]
