# Generated by Django 3.1 on 2020-08-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0006_auto_20200816_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitefacilities',
            name='laundry',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
    ]
