# Generated by Django 4.1.7 on 2023-03-30 12:37

from django.db import migrations
import mapbox_location_field.spatial.models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0007_auto_20210124_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinformation',
            name='location',
            field=mapbox_location_field.spatial.models.SpatialLocationField(blank=True, map_attrs={'center': [-0.82761, 51.18225], 'id': 'map_1', 'placeholder': 'Pick a location on the map below', 'style': 'mapbox://styles/mapbox/satellite-streets-v11'}, null=True, srid=4326),
        ),
    ]
