# Generated by Django 4.1.7 on 2023-03-30 13:42

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0008_alter_siteinformation_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinformation',
            name='address',
            field=mapbox_location_field.models.AddressAutoHiddenField(blank=True, map_id='map_1', null=True),
        ),
    ]
