# Generated by Django 3.1 on 2020-09-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0015_auto_20200907_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journeydetails',
            name='star_rating',
        ),
        migrations.RemoveField(
            model_name='journeydetails',
            name='would_return',
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='star_rating',
            field=models.CharField(blank=True, choices=[('', 'Choose...'), ('*', 'One Star'), ('**', 'Two Star'), ('***', 'Three Star'), ('****', 'Four Star'), ('*****', 'Five Star')], max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='would_return',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
