# Generated by Django 3.1 on 2020-10-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0018_merge_20200911_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinformation',
            name='star_rating',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
