# Generated by Django 3.1 on 2020-10-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0019_auto_20201014_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinformation',
            name='star_rating',
            field=models.IntegerField(blank=True, max_length=256, null=True),
        ),
    ]
