# Generated by Django 3.1 on 2020-10-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0022_auto_20201020_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinformation',
            name='star_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True),
        ),
    ]
