# Generated by Django 3.1 on 2020-10-22 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0024_auto_20201020_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeydetails',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
