# Generated by Django 3.1 on 2020-10-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0025_auto_20201022_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeydetails',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
