# Generated by Django 3.1 on 2020-10-22 19:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0026_auto_20201022_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeydetails',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 22, 19, 41, 7, 787315, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journeydetails',
            name='edited_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 22, 19, 41, 15, 404169, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='created_date',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='edited_date',
            field=models.DateTimeField(),
        ),
    ]
