# Generated by Django 3.1 on 2020-10-23 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0031_auto_20201023_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journeydetails',
            name='created_dt',
        ),
        migrations.RemoveField(
            model_name='journeydetails',
            name='edited_dt',
        ),
        migrations.RemoveField(
            model_name='siteinformation',
            name='created_dt',
        ),
        migrations.RemoveField(
            model_name='siteinformation',
            name='edited_dt',
        ),
    ]
