# Generated by Django 3.1 on 2020-10-23 10:44

from django.db import migrations, models
import django.utils.timezone
import triplog.models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0032_auto_20201023_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeydetails',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='journeydetails',
            name='edited',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=triplog.models.AutoDateTimeField),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='edited',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=triplog.models.AutoDateTimeField),
        ),
    ]
