# Generated by Django 3.1 on 2020-10-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0035_auto_20201023_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeydetails',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='journeydetails',
            name='edited_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='edited_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
