# Generated by Django 3.1 on 2020-10-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0041_remove_journeydetails_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='siteowner',
            field=models.CharField(blank=True, choices=[('CAMC CL', 'CAMC CL'), ('CAMC Site', 'CAMC Site'), ('C&CC CL', 'C&CC CL'), ('C&CC Site', 'C&CC Site'), ('Independent', 'Independent'), ('France Passion', 'France Passion'), ('n/a', 'n/a')], default='n/a', max_length=256),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='ambience',
            field=models.CharField(blank=True, choices=[('Peaceful', 'Peaceful'), ('OK', 'OK'), ('Loud/Lively', 'Loud/Lively')], default='Peaceful', max_length=256),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='children',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No'), (None, 'n/a')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='greeting',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Indifferent', 'Indifferent')], default='Good', max_length=256),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='hook_up',
            field=models.CharField(blank=True, choices=[('6A', '6A'), ('10A', '10A'), ('16A', '16A')], default='16A', max_length=256),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='laundry',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No'), (None, 'n/a')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='pets',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No'), (None, 'n/a')], default=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='phone_signal_3G_4G',
            field=models.CharField(blank=True, choices=[('Excellent 4G', 'Excellent 4G'), ('Good 4G', 'Good 4G'), ('Poor 4G', 'Poor 4G'), ('Excellent 3G', 'Excellent 3G'), ('Good 3G', 'Good 3G'), ('Poor 3G', 'Poor 3G')], default='Good 4G', max_length=256),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='pitch_level',
            field=models.CharField(blank=True, choices=[('Level', 'Level'), ('Gentle Slope', 'Gentle Slope'), ('Steep Slope', 'Steep Slope'), ('Impossible Slope', 'Impossible Slope')], default='Level', max_length=256),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='pitch_type',
            field=models.CharField(blank=True, choices=[('Dirt', 'Dirt'), ('Grass', 'Grass'), ('Hardstanding', 'Hardstanding')], default='Hardstanding', max_length=256),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='security',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Poor', 'Poor')], default='Good', max_length=256),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='toilets',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Clean', 'Clean'), ('Dirty', 'Dirty'), ("Don't Go There", "Don't Go There")], default='Clean', max_length=256),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='tv_signal',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Poor', 'Poor'), ('n/a', 'n/a')], default='n/a', max_length=256),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='waste',
            field=models.CharField(blank=True, choices=[('On Pitch', 'On Pitch'), ('Close By', 'Close By'), ('Miles Away', 'Miles Away')], default='Close By', max_length=256),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='wifi',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No'), (None, 'n/a')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='would_return',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No'), (None, 'n/a')], default=True, null=True),
        ),
    ]
