# Generated by Django 3.0.8 on 2020-08-05 08:59

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_latitude', models.FloatField()),
                ('site_longitude', models.FloatField()),
                ('site_name', models.CharField(max_length=256)),
                ('mpoly', djgeojson.fields.PointField()),
            ],
        ),
    ]
