# Generated by Django 3.0.8 on 2020-08-05 13:48

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemaps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
