# Generated by Django 3.1 on 2021-01-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemaps', '0002_auto_20200805_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoJSONRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_file', models.FileField(blank=True, null=True, upload_to='route/')),
                ('route_description', models.CharField(max_length=256)),
                ('route_name', models.CharField(max_length=256)),
            ],
        ),
    ]
