# Generated by Django 3.1 on 2021-01-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemaps', '0003_geojsonroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geojsonroute',
            name='route_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
