# Generated by Django 3.1 on 2021-01-25 18:28

from django.db import migrations, models
import sitemaps.models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemaps', '0004_auto_20210125_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geojsonroute',
            name='route_file',
            field=models.FileField(null=True, upload_to=sitemaps.models.user_directory_path),
        ),
    ]
