# Generated by Django 3.1 on 2021-01-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemaps', '0006_geojsonroute_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='geojsonroute',
            name='route_file_path',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
