# Generated by Django 3.1 on 2021-01-27 18:42

from django.db import migrations, models
import sitemaps.models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemaps', '0007_geojsonroute_route_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geojsonroute',
            name='route_file',
            field=models.FileField(null=True, storage=sitemaps.models.OverwriteStorage(), upload_to=sitemaps.models.user_directory_path),
        ),
    ]
