# Generated by Django 3.1 on 2021-02-03 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitemaps', '0008_auto_20210127_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='geojsonroute',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geojsonroute',
            name='edited_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
