# Generated by Django 3.1 on 2021-02-09 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemaps', '0009_auto_20210203_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geojsonroute',
            name='route_file_path',
        ),
    ]
