# Generated by Django 4.1.7 on 2023-03-30 12:37

from django.db import migrations, models
import sitemaps.models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemaps', '0010_remove_geojsonroute_route_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geojsonroute',
            name='route_file',
            field=models.FileField(null=True, storage=sitemaps.models.OverwriteStorage, upload_to=sitemaps.models.user_directory_path),
        ),
    ]
